apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kazy-prod
resources:
  - ../../base
  - hpa.yaml
  - ingress.yaml

images:
  - name: ghcr.io/benythomas/fineract
    newTag: main   # overlay expects :main; CI later sets image to the exact :<SHA>
