apiVersion: v1
kind: Service
metadata:
  name: fineract-server
  namespace: kazy-prod
  labels:
    app: fineract-server
spec:
  selector:
    app: fineract-server
    tier: backend
  ports:
    - name: http
      port: 8080
      targetPort: 8080
