name: Build & Deploy Fineract
on:
  push:
    branches: [ "main" ]
permissions:
  contents: read
  packages: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/fineract:main
            ghcr.io/${{ github.repository_owner }}/fineract:${{ github.sha }}

      - name: Rollout on cluster
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            kubectl -n kazy-prod set image deploy/fineract-server fineract-server=ghcr.io/${{ github.repository_owner }}/fineract:${{ github.sha }}
            kubectl -n kazy-prod rollout status deploy/fineract-server --timeout=5m
