name: Build & Push (GHCR)
on:
  push: { branches: [ "main" ] }
permissions: { contents: read, packages: write }
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/benythomas/fineract:prod
            ghcr.io/benythomas/fineract:${{ github.sha }}
